<?php

declare(strict_types=1);

namespace Framework\Tests\Unit\Http;

use Framework\Http\HttpKernel;
use Framework\Http\Request\Request;
use Framework\Http\Response\Response;
use Framework\Http\Router\Router;
use Framework\Tests\Support\RecordingLogger;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use RuntimeException;

#[CoversClass(HttpKernel::class)]
final class HttpKernelRequestIdTest extends TestCase
{
    public function testSuccessResponseIncludesXRequestIdHeader(): void
    {
        $router = new Router();
        $router->get('/x', static fn(): Response => Response::text('ok'));

        $kernel = new HttpKernel($router);
        $response = $kernel->handle(new Request('GET', '/x', '', [], '', null, null, null, [], null, null, null, 'success-id-1'));

        self::assertArrayHasKey('X-Request-Id', $response->headers);
        self::assertSame('success-id-1', $response->headers['X-Request-Id']);
    }

    public function testNotFoundResponseIncludesXRequestIdHeader(): void
    {
        $kernel = new HttpKernel(new Router());
        $response = $kernel->handle(new Request('GET', '/missing', '', [], '', null, null, null, [], null, null, null, 'notfound-id-2'));

        self::assertArrayHasKey('X-Request-Id', $response->headers);
        self::assertSame('notfound-id-2', $response->headers['X-Request-Id']);
    }

    public function testHttpExceptionResponseIncludesXRequestIdHeader(): void
    {
        $router = new Router();
        $router->get('/bad', static function (): void {
            throw new \Framework\Http\Exception\BadRequestHttpException('nope');
        });

        $kernel = new HttpKernel($router);
        $response = $kernel->handle(new Request('GET', '/bad', '', [], '', null, null, null, [], null, null, null, 'http-exc-id-3'));

        self::assertArrayHasKey('X-Request-Id', $response->headers);
        self::assertSame('http-exc-id-3', $response->headers['X-Request-Id']);
    }

    public function testUnhandledExceptionResponseIncludesXRequestIdHeader(): void
    {
        $router = new Router();
        $router->get('/crash', static function (): void {
            throw new RuntimeException('boom');
        });

        $kernel = new HttpKernel($router);
        $response = $kernel->handle(new Request('GET', '/crash', '', [], '', null, null, null, [], null, null, null, 'unhandled-id-4'));

        self::assertArrayHasKey('X-Request-Id', $response->headers);
        self::assertSame('unhandled-id-4', $response->headers['X-Request-Id']);
    }

    public function testAutoGeneratedIdEchoesBackOnSuccess(): void
    {
        $router = new Router();
        $router->get('/x', static fn(): Response => Response::text('ok'));

        $kernel = new HttpKernel($router);
        $request = new Request('GET', '/x');
        $response = $kernel->handle($request);

        self::assertArrayHasKey('X-Request-Id', $response->headers);
        self::assertSame($request->id, $response->headers['X-Request-Id']);
        self::assertMatchesRegularExpression('/\A[A-Fa-f0-9]{16}\z/', $response->headers['X-Request-Id']);
    }

    public function testErrorLogIncludesRequestIdMatchingResponseHeader(): void
    {
        $logger = new RecordingLogger();
        $kernel = new HttpKernel(new Router(), null, null, $logger);
        $request = new Request('GET', '/missing', '', [], '', null, null, null, [], null, null, null, 'log-corr-id-5');
        $response = $kernel->handle($request);

        self::assertCount(1, $logger->records);
        self::assertSame('log-corr-id-5', $logger->records[0]['context']['request_id']);
        self::assertSame($response->headers['X-Request-Id'], $logger->records[0]['context']['request_id']);
    }

    public function testUnhandledExceptionLogIncludesRequestIdMatchingResponseHeader(): void
    {
        $logger = new RecordingLogger();
        $router = new Router();
        $router->get('/crash', static function (): void {
            throw new RuntimeException('boom');
        });
        $kernel = new HttpKernel($router, null, null, $logger);
        $request = new Request('GET', '/crash', '', [], '', null, null, null, [], null, null, null, 'unhandled-log-6');
        $response = $kernel->handle($request);

        self::assertCount(1, $logger->records);
        self::assertSame('unhandled-log-6', $logger->records[0]['context']['request_id']);
        self::assertSame('unhandled-log-6', $response->headers['X-Request-Id']);
    }

    public function testFiveXxHttpExceptionLogIncludesRequestId(): void
    {
        $logger = new RecordingLogger();
        $router = new Router();
        $router->get('/fail', static function (): void {
            throw new \Framework\Http\Exception\InternalServerErrorHttpException('down');
        });
        $kernel = new HttpKernel($router, null, null, $logger);
        $request = new Request('GET', '/fail', '', [], '', null, null, null, [], null, null, null, 'fivexx-id-7');
        $kernel->handle($request);

        self::assertCount(1, $logger->records);
        self::assertSame('fivexx-id-7', $logger->records[0]['context']['request_id']);
    }
}
