<?php

declare(strict_types=1);

/**
 * Example: a realistic mini-app showcasing the framework's flagship features
 * for a typical web application — HTML forms with CSRF protection, signed
 * session cookies, JSON API endpoints with DTO validation, and logout.
 * Mirrors a real `public/index.php` for a small authenticated dashboard.
 *
 * Routes: GET /login, POST /login, GET /dashboard, POST /api/users, POST /logout.
 * Pipeline: parsers → CSRF → handler. Form parser hydrates `_token` BEFORE
 * CsrfMiddleware checks it; CSRF short-circuits unsafe methods with 400.
 */

namespace Framework\Examples;

use Framework\Container\Container;
use Framework\Http\Exception\UnauthorizedHttpException;
use Framework\Http\HttpKernel;
use Framework\Http\Middleware\FormBodyParser;
use Framework\Http\Middleware\JsonBodyParser;
use Framework\Http\Middleware\Pipeline;
use Framework\Http\Request\Request;
use Framework\Http\Response\Response;
use Framework\Http\Router\Router;
use Framework\Logging\LoggerInterface;
use Framework\Logging\NullLogger;
use Framework\Security\CsrfMiddleware;
use Framework\Security\SignedCookieJar;
use Framework\Validation\Attribute\Validate;
use Framework\Validation\Rule\RuleRegistry;
use Framework\Validation\Validator;

require_once __DIR__ . '/../vendor/autoload.php';

// Container: lazy singletons keep boot O(1); the signed jar is shared so
// the HMAC state is built once and reused per request.
$container = new Container();
$container->set(LoggerInterface::class, static fn(): LoggerInterface => new NullLogger());
$container->set(RuleRegistry::class, static fn(): RuleRegistry => new RuleRegistry());
$container->set(Validator::class, static fn(Container $c): Validator
    => new Validator($c->get(RuleRegistry::class)));
// SignedCookieJar HMACs every session value with APP_SECRET; a forged
// `session=alice.signature` cannot pass `payload()` without the key.
$container->set(SignedCookieJar::class, static fn(): SignedCookieJar => new SignedCookieJar(
    secret: getenv('APP_SECRET') ?: 'dev-only-secret-change-in-prod',
));
$container->set(CsrfMiddleware::class, static fn(Container $c): CsrfMiddleware => new CsrfMiddleware(
    jar: $c->get(SignedCookieJar::class),
    exemptPrefixes: ['/api/'], // JSON APIs use X-CSRF-Token or bearer auth.
));

// "make:dto" style — in a real app: `src/Validation/Dto/CreateUserRequest.php`
// (generated by `bin/framework make:dto CreateUser`). `final readonly` DTO;
// the binder reads #[Validate] attributes via reflection.
final readonly class CreateUserRequest
{
    public function __construct(
        #[Validate(['required', 'string', 'min:2', 'max:50'])] public ?string $name = null,
        #[Validate(['required', 'email'])] public ?string $email = null,
        #[Validate(['required', 'integer'])] public ?int $age = null,
    ) {}
}

// "make:controller" style — in a real app: `src/Http/Controller/AuthController.php`.
// Plain `final readonly`; handler methods take `(Request, array)` per the
// Router contract and pull their dependencies from the Container.
final readonly class AuthController
{
    public function __construct(private readonly SignedCookieJar $jar) {}

    public function showLogin(Request $r): Response
    {
        // $r->csrfToken() is populated by CsrfMiddleware from the signed
        // cookie. The hidden field binds the token to THIS session; a
        // cross-site form cannot read it.
        $t = htmlspecialchars((string) $r->csrfToken(), ENT_QUOTES);
        return Response::html("<form method=POST action=/login>"
            . "<input type=hidden name=_token value='{$t}'>"
            . '<input name=user value=alice><input name=pass type=password value=secret>'
            . '<button>Sign in</button></form>');
    }

    public function submitLogin(Request $r): Response
    {
        // CsrfMiddleware already validated `_token` BEFORE this handler;
        // bad creds → 401 problem+json.
        $f = $r->form() ?? [];
        if (($f['user'] ?? null) !== 'alice' || ($f['pass'] ?? null) !== 'secret') {
            throw new UnauthorizedHttpException('Invalid credentials');
        }
        // Stash the username in a signed session cookie; the next request
        // verifies the HMAC and recovers the original payload.
        return Response::redirect('/dashboard', 303)
            ->withCookie($this->jar->makeCookie('session', 'alice', expiresAt: time() + 3600));
    }

    public function dashboard(Request $r): Response
    {
        $user = $this->jar->read($r, 'session');
        return $user === null
            ? throw new UnauthorizedHttpException('Sign in first')
            : Response::html('<h1>Hello, ' . htmlspecialchars($user, ENT_QUOTES) . '</h1>');
    }

    public function logout(): Response
    {
        // Re-issue the cookie empty + Max-Age=0; the browser drops it. The
        // jar still signs the empty payload so Set-Cookie stays well-formed.
        return Response::redirect('/login', 303)->withCookie($this->jar->makeCookie('session', ''));
    }

    public function createUser(Request $r): Response
    {
        // $r->bind() runs the Validator pipeline: reads #[Validate] attrs,
        // resolves rules from RuleRegistry, returns a hydrated DTO. Throws
        // ValidationException → 422 application/problem+json.
        /** @var CreateUserRequest $user */
        $user = $r->bind(CreateUserRequest::class);
        return Response::json(['name' => $user->name, 'email' => $user->email, 'age' => $user->age], 201);
    }
}

$router = new Router();
$auth = new AuthController($container->get(SignedCookieJar::class));
$router->get('/login', $auth->showLogin(...));
$router->post('/login', $auth->submitLogin(...));
$router->get('/dashboard', $auth->dashboard(...));
$router->post('/api/users', $auth->createUser(...));
$router->post('/logout', $auth->logout(...));

// Pipeline: parsers → CSRF → handler. Parsers hydrate the body BEFORE CSRF
// reads `_token`; CSRF rejects unsafe methods with 400 before the handler.
$pipeline = new Pipeline($container);
$pipeline->pipe(JsonBodyParser::class);
$pipeline->pipe(FormBodyParser::class);
$pipeline->pipe(CsrfMiddleware::class);

$kernel = new HttpKernel($router, $pipeline, $container, debug: true);
$kernel->handle(Request::fromGlobals()->withValidator($container->get(Validator::class)))->send();
