name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Tag ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print version
        run: |
          echo "Tag: ${GITHUB_REF_NAME#v}"
          grep "public const string VERSION" src/Framework.php

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/.composer-cache
          key: php-8.5-${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-8.5-${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run checks
        run: composer check

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
